services:  
  # DB: mariaDB
  db:
    image: mariadb:11
    container_name: redbox-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: redbox_db
    ports:
      - "3306:3306"
    volumes:
      - redbox_db_data:/var/lib/mysql

  # Cache & Chat: Redis
  redis:
    image: redis:7-alpine
    container_name: redbox-redis
    restart: always
    ports:
      - "6379:6379"

  # MinIO (S3 Object Storage)
  minio:
    image: minio/minio:latest
    container_name: redbox-minio
    restart: always
    environment:
      MINIO_ROOT_USER: "admin_redbox"
      MINIO_ROOT_PASSWORD: "SuperSecretMinioPassword123"
    ports:
      - "9000:9000" # API Port (Backend)
      - "9001:9001" # Web-Interface Port (Browser)
    volumes:
      - D:/redbox-minio:/data #/path/to/hdd/minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  redbox_db_data: