# syntax=docker/dockerfile:1

FROM node:22-alpine AS build

WORKDIR /app

RUN apk add --no-cache openssl \
  && corepack enable

COPY apps/backend/package.json apps/backend/pnpm-lock.yaml apps/backend/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY apps/backend ./
RUN pnpm prisma generate
RUN pnpm build

FROM node:22-alpine AS runtime

ENV NODE_ENV=production
WORKDIR /app

RUN apk add --no-cache openssl \
  && corepack enable

COPY --from=build /app/package.json /app/pnpm-lock.yaml /app/pnpm-workspace.yaml ./
COPY --from=build /app/prisma ./prisma
RUN pnpm install --frozen-lockfile && pnpm prisma generate
COPY --from=build /app/dist ./dist

EXPOSE 3000 3001

CMD ["node", "dist/src/main"]
